name: Deploy to AWS Elastic Beanstalk

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4.1.1

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '8.0'  

    - name: Build and Publish
      run: |
        dotnet restore OpenSourceRecipe/OpenSourceRecipe.csproj
        dotnet publish OpenSourceRecipe/OpenSourceRecipe.csproj -c Release -o ./publish

    - name: Zip
      run: zip -r deploy.zip ./publish

    - name: Deploy to Elastic Beanstalk
      uses: einaregilsson/beanstalk-deploy@v21
      with:
        aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        application_name: recipe-hub
        environment_name: Recipe-hub-env
        version_label: ${{ github.sha }}
        region: us-east-1
        deployment_package: deploy.zip
